config/routes.rb
RealEstate::Application.routes.draw do
  resources :tenants

  resources :owners

  resources :buildings

  root 'buildings#index'

  

end

app/models/building.rb
class Building < ActiveRecord::Base
  belongs_to :owner,
    inverse_of: :buildings
  has_many :tenants,
    through: :owner,
    inverse_of: :building

  validates_presence_of :street_address
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :postal_code

  validates_length_of :postal_code, :is=>5
  validates_format_of :postal_code, 
    :with => /\d{5}/

  def self.states
    [
      ['AK'],
      ['AL'],
      ['AR'],
      ['AZ'],
      ['CA'],
      ['CO'],
      ['CT'],
      ['DC'],
      ['DE'],
      ['FL'],
      ['GA'],
      ['HI'],
      ['IA'],
      ['ID'],
      ['IL'],
      ['IN'],
      ['KS'],
      ['KY'],
      ['LA'],
      ['MA'],
      ['MD'],
      ['ME'],
      ['MI'],
      ['MN'],
      ['MO'],
      ['MS'],
      ['MT'],
      ['NC'],
      ['ND'],
      ['NE'],
      ['NH'],
      ['NJ'],
      ['NM'],
      ['NV'],
      ['NY'],
      ['OH'],
      ['OK'],
      ['OR'],
      ['PA'],
      ['RI'],
      ['SC'],
      ['SD'],
      ['TN'],
      ['TX'],
      ['UT'],
      ['VA'],
      ['VT'],
      ['WA'],
      ['WI'],
      ['WV'],
      ['WY']
    ]
  end
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :buildings,
    inverse_of: :owner,
    dependent: :nullify #If delete owner then delete any relationship with building

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email

  validates_format_of :email, 
    :with => /.+@.+\..+/i

  def full_name
    [first_name, last_name].join(' ')
  end
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
  belongs_to :building
  belongs_to :owner

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :building_id
  validates_presence_of :email

  validates_numericality_of :building_id

  validates_format_of :email, 
    :with => /.+@.+\..+/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  def index
  end
  
  def new
    @building = Building.new
  end

  def create
    @building = Building.new(building_params)
    if @building.save
      redirect_to new_building_path,
      notice: "Building successfully added!"
    else
      render :new
    end
  end

  protected
  def building_params
    params.require(:building).permit(:street_address, :city, :state, :postal_code, :description, :owner_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(owner_params)
    if @owner.save
      redirect_to new_owner_path,
      notice: "Owner Successfully Added"
    else
      render :new
    end
  end

  protected
  def owner_params
    params.require(:owner).permit(:first_name, :last_name, :email, :company)
  end

end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  def index
    @tenant = Tenant.all.order('last_name', 'first_name')
  end

  def new
    @tenant = Tenant.new
  end

  def create
    @tenant = Tenant.new(tenant_params)
    if @tenant.save
      redirect_to new_tenant_path,
      notice: "Tenant successfully added"
    else
      render :new
    end
  end

  def destroy
    @tenant = Tenant.find(params[:id])
    @tenant.destroy
    respond_to do |format|
      format.html { redirect_to tenants_path }
    end
  end

  protected
  def tenant_params
    params.require(:tenant).permit(:first_name, :last_name, :building_id, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/buildings/index.html.erb
<h1 class="welcome">Welcome Real Estate Associate!</h1>

<div class="add-new">
<h3>If you would like to add a new building:</h3>
<%= link_to 'Add New Building', new_building_path %>
</div>

<div class="add-new">
<h3>If you would like to add a new building owner:</h3>
<%= link_to 'Add New Owner', new_owner_path %>
</div>

<div class="add-new">
<h3>If you would like to view all or add tenants:</h3>
<%= link_to 'View Tenants', tenants_path %><br>
<%= link_to 'Add New Tenant', new_tenant_path %>
</div>

app/views/buildings/new.html.erb
<%- if @building.errors.size > 0 -%>
  <ul class="errors">
    <%- @building.errors.full_messages.each do |message| -%>
    <li><strong><%= message %></strong></li>
    <%- end -%>
  </ul>
<%- end -%>

<h2>Add a Building</h2>

<%= form_for @building do |f| %>
  <div>
    <%= f.label :street_address, 'Street Address' %>
    <%= f.text_field :street_address %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.select :state, Building.states, include_blank: true %>
  </div>
  <div>
    <%= f.label :postal_code, 'Postal Code' %>
    <%= f.text_field :postal_code %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description, size: "25x3" %>
  </div><br>
  <div>Optional Owner Information</div>
    <div>
    <%# f.label :owner_id, "Owner ID" %>
    <%# f.text_field :owner_id %>

    <%= f.label :owner_id %><br>
    <%= f.select :owner_id, options_for_select(Owner.all.map{|owner| [owner.full_name, owner.id]}.unshift(["",""])) %>

  </div>

  <% if false %>
  <div>
    <%= f.fields_for :owner do |ff| %>
      <div>
        <%= ff.label :first_name, 'Owner First Name' %>
        <%= ff.text_field :first_name %>
      </div>
      <div>
        <%= ff.label :last_name, 'Owner Last Name' %>
        <%= ff.text_field :last_name %>
      </div>
      <div>
        <%= ff.label :email, 'Owner Email' %>
        <%= ff.text_field :email %>
      </div>
    <% end %>
  </div>
  <%- end -%>
  
  <div>
    <%= f.submit 'Add Building' %>
  </div>

<%- end -%>

<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RealEstate</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <style>
  html {
    background-color: #FDD7E4;
    font-family: Helvetica, sans-serif;
  }
  .welcome {
    text-align: center;
  }
  .add-new {
    text-align: center;
    display: block;
    border: 1px solid gray;
  }
  th {
    border-bottom: 1px solid black;
    padding: 3px;
  }
  td {
    text-align: center;
  }
  </style>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%><br />

<%= yield %>

</body>
</html>

app/views/owners/new.html.erb
<%- if @owner.errors.size > 0 -%>
  <ul class="errors">
    <%- @owner.errors.full_messages.each do |message| -%>
    <li><strong><%= message %></strong></li>
    <%- end -%>
  </ul>
<%- end -%>

<h2>Add an Owner</h2>

<%= form_for @owner do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :company %>
    <%= f.text_field :company %>
  </div>
  <div>
    <%= f.submit 'Add Owner' %>
  </div>

<%- end -%>

<%= link_to 'Back', root_path %>

app/views/tenants/index.html.erb
<h1>Tenants</h1>

<table>
  <thead>
    <tr>
      <th>Last Name</th>
      <th>First Name</th>
      <th>Building ID</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @tenant.each do |person| %>
    <tr>
      <td><%= person.last_name %></td>
      <td><%= person.first_name %></td>
      <td><%= person.building_id %></td>
      <td><%= person.email %></td>
      <td><%= link_to 'Evict', person, method: :delete, data: { confirm: 'You really want to do this?' } %></td>
    <% end %>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'Add Tenant', new_tenant_path %><br>
<%= link_to 'Back', buildings_path %>

app/views/tenants/new.html.erb
<%- if @tenant.errors.size > 0 -%>
  <ul class="errors">
    <%- @tenant.errors.full_messages.each do |message| -%>
    <li><strong><%= message %></strong></li>
    <%- end -%>
  </ul>
<%- end -%>

<h2>Add a Tenant</h2>

<%= form_for @tenant do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :building_id, "Building ID" %>
    <%= f.text_field :building_id %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :owner_id, "Owner ID" %>
    <%= f.text_field :owner_id %>
  </div>

  <div>
    <%= f.submit 'Add Tenant' %>
  </div>

<%- end -%>

<%= link_to 'Back', root_path %>